modLoader="javafml"
loaderVersion="[4,)"
license="${license}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="CreeperSense"
description='''${description}'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${id}]]
modId="neoforge"
type="required"
versionRange="[${forge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${mcdep}"
ordering="NONE"
side="CLIENT"

